// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.2
// source: proto/vectordb.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InsertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Vector        []float32              `protobuf:"fixed32,2,rep,packed,name=vector,proto3" json:"vector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertRequest) Reset() {
	*x = InsertRequest{}
	mi := &file_proto_vectordb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertRequest) ProtoMessage() {}

func (x *InsertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vectordb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertRequest.ProtoReflect.Descriptor instead.
func (*InsertRequest) Descriptor() ([]byte, []int) {
	return file_proto_vectordb_proto_rawDescGZIP(), []int{0}
}

func (x *InsertRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InsertRequest) GetVector() []float32 {
	if x != nil {
		return x.Vector
	}
	return nil
}

type InsertResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Success         bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message         string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RoutedToShard   string                 `protobuf:"bytes,3,opt,name=routed_to_shard,json=routedToShard,proto3" json:"routed_to_shard,omitempty"`
	ExecutionTimeNs int64                  `protobuf:"varint,4,opt,name=execution_time_ns,json=executionTimeNs,proto3" json:"execution_time_ns,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InsertResponse) Reset() {
	*x = InsertResponse{}
	mi := &file_proto_vectordb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertResponse) ProtoMessage() {}

func (x *InsertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vectordb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertResponse.ProtoReflect.Descriptor instead.
func (*InsertResponse) Descriptor() ([]byte, []int) {
	return file_proto_vectordb_proto_rawDescGZIP(), []int{1}
}

func (x *InsertResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *InsertResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *InsertResponse) GetRoutedToShard() string {
	if x != nil {
		return x.RoutedToShard
	}
	return ""
}

func (x *InsertResponse) GetExecutionTimeNs() int64 {
	if x != nil {
		return x.ExecutionTimeNs
	}
	return 0
}

type QueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vector        []float32              `protobuf:"fixed32,1,rep,packed,name=vector,proto3" json:"vector,omitempty"`
	K             int32                  `protobuf:"varint,2,opt,name=k,proto3" json:"k,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_proto_vectordb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vectordb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_proto_vectordb_proto_rawDescGZIP(), []int{2}
}

func (x *QueryRequest) GetVector() []float32 {
	if x != nil {
		return x.Vector
	}
	return nil
}

func (x *QueryRequest) GetK() int32 {
	if x != nil {
		return x.K
	}
	return 0
}

type VectorMatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Score         float32                `protobuf:"fixed32,2,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VectorMatch) Reset() {
	*x = VectorMatch{}
	mi := &file_proto_vectordb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorMatch) ProtoMessage() {}

func (x *VectorMatch) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vectordb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorMatch.ProtoReflect.Descriptor instead.
func (*VectorMatch) Descriptor() ([]byte, []int) {
	return file_proto_vectordb_proto_rawDescGZIP(), []int{3}
}

func (x *VectorMatch) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VectorMatch) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type QueryResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Matches         []*VectorMatch         `protobuf:"bytes,1,rep,name=matches,proto3" json:"matches,omitempty"`
	ExecutionTimeNs int64                  `protobuf:"varint,2,opt,name=execution_time_ns,json=executionTimeNs,proto3" json:"execution_time_ns,omitempty"`
	RoutedToShard   string                 `protobuf:"bytes,3,opt,name=routed_to_shard,json=routedToShard,proto3" json:"routed_to_shard,omitempty"`
	IndexType       string                 `protobuf:"bytes,4,opt,name=index_type,json=indexType,proto3" json:"index_type,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_proto_vectordb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vectordb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_proto_vectordb_proto_rawDescGZIP(), []int{4}
}

func (x *QueryResponse) GetMatches() []*VectorMatch {
	if x != nil {
		return x.Matches
	}
	return nil
}

func (x *QueryResponse) GetExecutionTimeNs() int64 {
	if x != nil {
		return x.ExecutionTimeNs
	}
	return 0
}

func (x *QueryResponse) GetRoutedToShard() string {
	if x != nil {
		return x.RoutedToShard
	}
	return ""
}

func (x *QueryResponse) GetIndexType() string {
	if x != nil {
		return x.IndexType
	}
	return ""
}

type StatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsRequest) Reset() {
	*x = StatsRequest{}
	mi := &file_proto_vectordb_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsRequest) ProtoMessage() {}

func (x *StatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vectordb_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsRequest.ProtoReflect.Descriptor instead.
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_vectordb_proto_rawDescGZIP(), []int{5}
}

type ShardStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	VectorCount   int64                  `protobuf:"varint,2,opt,name=vector_count,json=vectorCount,proto3" json:"vector_count,omitempty"`
	MaxLayer      int32                  `protobuf:"varint,3,opt,name=max_layer,json=maxLayer,proto3" json:"max_layer,omitempty"`
	EfSearch      int32                  `protobuf:"varint,4,opt,name=ef_search,json=efSearch,proto3" json:"ef_search,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShardStats) Reset() {
	*x = ShardStats{}
	mi := &file_proto_vectordb_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShardStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardStats) ProtoMessage() {}

func (x *ShardStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vectordb_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardStats.ProtoReflect.Descriptor instead.
func (*ShardStats) Descriptor() ([]byte, []int) {
	return file_proto_vectordb_proto_rawDescGZIP(), []int{6}
}

func (x *ShardStats) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ShardStats) GetVectorCount() int64 {
	if x != nil {
		return x.VectorCount
	}
	return 0
}

func (x *ShardStats) GetMaxLayer() int32 {
	if x != nil {
		return x.MaxLayer
	}
	return 0
}

func (x *ShardStats) GetEfSearch() int32 {
	if x != nil {
		return x.EfSearch
	}
	return 0
}

func (x *ShardStats) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type StatsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TotalVectors   int64                  `protobuf:"varint,1,opt,name=total_vectors,json=totalVectors,proto3" json:"total_vectors,omitempty"`
	WorkerPoolSize int32                  `protobuf:"varint,2,opt,name=worker_pool_size,json=workerPoolSize,proto3" json:"worker_pool_size,omitempty"`
	IndexType      string                 `protobuf:"bytes,3,opt,name=index_type,json=indexType,proto3" json:"index_type,omitempty"`
	MaxLayer       int32                  `protobuf:"varint,4,opt,name=max_layer,json=maxLayer,proto3" json:"max_layer,omitempty"`
	EfSearch       int32                  `protobuf:"varint,5,opt,name=ef_search,json=efSearch,proto3" json:"ef_search,omitempty"`
	Shards         []*ShardStats          `protobuf:"bytes,6,rep,name=shards,proto3" json:"shards,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_proto_vectordb_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vectordb_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_vectordb_proto_rawDescGZIP(), []int{7}
}

func (x *StatsResponse) GetTotalVectors() int64 {
	if x != nil {
		return x.TotalVectors
	}
	return 0
}

func (x *StatsResponse) GetWorkerPoolSize() int32 {
	if x != nil {
		return x.WorkerPoolSize
	}
	return 0
}

func (x *StatsResponse) GetIndexType() string {
	if x != nil {
		return x.IndexType
	}
	return ""
}

func (x *StatsResponse) GetMaxLayer() int32 {
	if x != nil {
		return x.MaxLayer
	}
	return 0
}

func (x *StatsResponse) GetEfSearch() int32 {
	if x != nil {
		return x.EfSearch
	}
	return 0
}

func (x *StatsResponse) GetShards() []*ShardStats {
	if x != nil {
		return x.Shards
	}
	return nil
}

var File_proto_vectordb_proto protoreflect.FileDescriptor

const file_proto_vectordb_proto_rawDesc = "" +
	"\n" +
	"\x14proto/vectordb.proto\x12\bvectordb\"7\n" +
	"\rInsertRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06vector\x18\x02 \x03(\x02R\x06vector\"\x98\x01\n" +
	"\x0eInsertResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12&\n" +
	"\x0frouted_to_shard\x18\x03 \x01(\tR\rroutedToShard\x12*\n" +
	"\x11execution_time_ns\x18\x04 \x01(\x03R\x0fexecutionTimeNs\"4\n" +
	"\fQueryRequest\x12\x16\n" +
	"\x06vector\x18\x01 \x03(\x02R\x06vector\x12\f\n" +
	"\x01k\x18\x02 \x01(\x05R\x01k\"3\n" +
	"\vVectorMatch\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x02R\x05score\"\xb3\x01\n" +
	"\rQueryResponse\x12/\n" +
	"\amatches\x18\x01 \x03(\v2\x15.vectordb.VectorMatchR\amatches\x12*\n" +
	"\x11execution_time_ns\x18\x02 \x01(\x03R\x0fexecutionTimeNs\x12&\n" +
	"\x0frouted_to_shard\x18\x03 \x01(\tR\rroutedToShard\x12\x1d\n" +
	"\n" +
	"index_type\x18\x04 \x01(\tR\tindexType\"\x0e\n" +
	"\fStatsRequest\"\x9a\x01\n" +
	"\n" +
	"ShardStats\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12!\n" +
	"\fvector_count\x18\x02 \x01(\x03R\vvectorCount\x12\x1b\n" +
	"\tmax_layer\x18\x03 \x01(\x05R\bmaxLayer\x12\x1b\n" +
	"\tef_search\x18\x04 \x01(\x05R\befSearch\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\"\xe5\x01\n" +
	"\rStatsResponse\x12#\n" +
	"\rtotal_vectors\x18\x01 \x01(\x03R\ftotalVectors\x12(\n" +
	"\x10worker_pool_size\x18\x02 \x01(\x05R\x0eworkerPoolSize\x12\x1d\n" +
	"\n" +
	"index_type\x18\x03 \x01(\tR\tindexType\x12\x1b\n" +
	"\tmax_layer\x18\x04 \x01(\x05R\bmaxLayer\x12\x1b\n" +
	"\tef_search\x18\x05 \x01(\x05R\befSearch\x12,\n" +
	"\x06shards\x18\x06 \x03(\v2\x14.vectordb.ShardStatsR\x06shards2\xc3\x01\n" +
	"\rVectorService\x12;\n" +
	"\x06Insert\x12\x17.vectordb.InsertRequest\x1a\x18.vectordb.InsertResponse\x128\n" +
	"\x05Query\x12\x16.vectordb.QueryRequest\x1a\x17.vectordb.QueryResponse\x12;\n" +
	"\bGetStats\x12\x16.vectordb.StatsRequest\x1a\x17.vectordb.StatsResponseB\x15Z\x13vector-engine/protob\x06proto3"

var (
	file_proto_vectordb_proto_rawDescOnce sync.Once
	file_proto_vectordb_proto_rawDescData []byte
)

func file_proto_vectordb_proto_rawDescGZIP() []byte {
	file_proto_vectordb_proto_rawDescOnce.Do(func() {
		file_proto_vectordb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_vectordb_proto_rawDesc), len(file_proto_vectordb_proto_rawDesc)))
	})
	return file_proto_vectordb_proto_rawDescData
}

var file_proto_vectordb_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_vectordb_proto_goTypes = []any{
	(*InsertRequest)(nil),  // 0: vectordb.InsertRequest
	(*InsertResponse)(nil), // 1: vectordb.InsertResponse
	(*QueryRequest)(nil),   // 2: vectordb.QueryRequest
	(*VectorMatch)(nil),    // 3: vectordb.VectorMatch
	(*QueryResponse)(nil),  // 4: vectordb.QueryResponse
	(*StatsRequest)(nil),   // 5: vectordb.StatsRequest
	(*ShardStats)(nil),     // 6: vectordb.ShardStats
	(*StatsResponse)(nil),  // 7: vectordb.StatsResponse
}
var file_proto_vectordb_proto_depIdxs = []int32{
	3, // 0: vectordb.QueryResponse.matches:type_name -> vectordb.VectorMatch
	6, // 1: vectordb.StatsResponse.shards:type_name -> vectordb.ShardStats
	0, // 2: vectordb.VectorService.Insert:input_type -> vectordb.InsertRequest
	2, // 3: vectordb.VectorService.Query:input_type -> vectordb.QueryRequest
	5, // 4: vectordb.VectorService.GetStats:input_type -> vectordb.StatsRequest
	1, // 5: vectordb.VectorService.Insert:output_type -> vectordb.InsertResponse
	4, // 6: vectordb.VectorService.Query:output_type -> vectordb.QueryResponse
	7, // 7: vectordb.VectorService.GetStats:output_type -> vectordb.StatsResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_vectordb_proto_init() }
func file_proto_vectordb_proto_init() {
	if File_proto_vectordb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_vectordb_proto_rawDesc), len(file_proto_vectordb_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_vectordb_proto_goTypes,
		DependencyIndexes: file_proto_vectordb_proto_depIdxs,
		MessageInfos:      file_proto_vectordb_proto_msgTypes,
	}.Build()
	File_proto_vectordb_proto = out.File
	file_proto_vectordb_proto_goTypes = nil
	file_proto_vectordb_proto_depIdxs = nil
}
